name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2019
        node_version:
          - 12.18.3
          - 14
        arch:
          - x64
        pnpm:
          - 6
        include:
          - os: windows-2019
            node_version: 12.18.3
            arch: x86
            pnpm: 6
          - os: windows-2019
            node_version: 14
            arch: x86
            pnpm: 6
    env:
      arch: ${{ matrix.arch }}
      npm_config_arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            D:\.pnpm-store
            ./node_modules/
            ~/npm-cache
            ~/.pnpm-store
            D:\.pnpm-store
            ./bin/node
            ./bin/node.exe
          key: "cache-OS:${{ matrix.os }}-${{ matrix.arch }}-pnpm:${{ matrix.pnpm }}-node:${{ matrix.node_version }}-${{ hashFiles('./package.json') }}-${{ hashFiles('./.npmrc') }}"

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.arch }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build
        if: steps.cache.outputs.cache-hit == 'true'
        run: pnpm run prepare

      - name: Run tests
        run: ./bin/pnpm test

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commit lint ✨
        uses: wagoid/commitlint-github-action@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: |
          pnpm install --ignore-scripts
          pnpm run prepare

      - name: Format ✨
        run: pnpm run test.format

      - name: Lint ✨
        run: pnpm run test.lint
